#!/bin/sh

cd %teamcity.build.checkoutDir%

git=$(sh /etc/profile; which git)

publish=1


#disable Publish if we are not on master
if [ "%vcsroot.branch%" != "refs/heads/master" ];
then 
 echo "***Not on master"
 publish=0
else
 echo "***On master"
fi


#disable publish if the the HEAD doesn't have a tag
headHasTag=`git show-ref --tags | grep \`git rev-parse HEAD\``

if [ "$headHasTag" == "" ];
then 
 echo "***No tag on head"
 publish=0
else
 echo "***Tag on Head"
fi




if [ $publish == 1 ];
then
  echo "***Publish Framework"

  number_of_commits=$("$git" rev-list HEAD --count)
  git_release_version=$("$git" describe --tags --always --abbrev=0)
  mv %teamcity.build.checkoutDir%/QredoXDK.framework ~/ios_build/
  cd ~/ios_build/
  git add -A
  export GIT_SSH_COMMAND="ssh -i ~/.ssh/ios_build -F /dev/null"
  GIT_SSH_COMMAND="ssh -i ~/.ssh/ios_build -F /dev/null"
  git commit -m "Build - $number_of_commits [%build.number%] Version - $git_release_version"
  git push
  rm -rf QredoXDK.framework
else
	echo "***Not published"
fi