//
//  QredoIndexModel.h
//  All objects in the Model QredoLocalIndex.xcdatamodel
//  That represents objects in CoreData
//
//  Each of these included files all inherit from a similar filename prefixed with an underscore
//  These underscore files are generated by mogenerator, and wrap coredata access with  helper methods
//
//  Created by Christopher Morris on 19/01/2016.
//
//


#import "QredoIndexVaultItemPayload.h"
#import "QredoIndexVault.h"
#import "QredoIndexSummaryValues.h"
#import "QredoIndexVaultItem.h"
#import "QredoIndexVaultItemDescriptor.h"
#import "QredoIndexVaultItemMetadata.h"
#import "QredoIndexVariableValue.h"
