#!/bin/sh

current_dir=$(pwd)
cd $(dirname $0)
script_dir=$(pwd)
cd ${current_dir}
base_path=$(dirname $(dirname $script_dir)) # This is the dir where you have checked out all repos


qredo_sdk_version="0.2.0"
lingua_franca_version=$(cat $base_path/lingua-franca/pom.xml | grep -m 1 "<version>" | sed -e 's/<[^>]*>//g' | tr -d '\t\n ')

input_paths="${base_path}/common-definitions/src/main/lf/common:${base_path}/common-definitions/src/main/lf/internal:${base_path}/common-definitions/src/main/lf/services"
output_dir="${base_path}/qredo_ios_sdk/QredoSDK/Internal/Autogenerated"
compiler_jar_file="${base_path}/lingua-franca/compiler/target/compiler-${lingua_franca_version}.jar"


java -jar "$compiler_jar_file" "$input_paths" "$output_dir" -f objc -n QLF -r $qredo_sdk_version

